<?php

/**
 * Basecomment
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $post_id
 * @property string $name
 * @property string $description
 * @property post $post
 * 
 * @method integer getPostId()      Returns the current record's "post_id" value
 * @method string  getName()        Returns the current record's "name" value
 * @method string  getDescription() Returns the current record's "description" value
 * @method post    getPost()        Returns the current record's "post" value
 * @method comment setPostId()      Sets the current record's "post_id" value
 * @method comment setName()        Sets the current record's "name" value
 * @method comment setDescription() Sets the current record's "description" value
 * @method comment setPost()        Sets the current record's "post" value
 * 
 * @package    blog
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class Basecomment extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('comment');
        $this->hasColumn('post_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('description', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('post', array(
             'local' => 'post_id',
             'foreign' => 'id',
             'onDelete' => 'cascade'));
    }
}