homepage:
  url:   /
  param: { module: dashboard, action: index }

posts:
  class:    sfDoctrineRouteCollection
  options:  { module: posts, model: post }

langage:
  url:   /language
  param: { module: changeLanguage, action: index }