homepage:
  url:   /
  param: { module: dashboard, action: index }

posts:
  class:    sfDoctrineRouteCollection
  options:  { module: posts, model: post }

langage:
  url:   /language
  param: { module: changeLanguage, action: index }
  
comments:
  class:    sfDoctrineRouteCollection
  options:  { module: comments, model: comment, prefix_path: /posts/:post_id/comments }  