<?php

/**
 * postTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class postTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object postTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('post');
    }
    
    public function getAll()
    {
        
         $q = $this->createQuery('c')
         ->leftJoin('c.comments a')
         ->orderBy('c.id DESC');
                 
         return $q->execute();
        
    }
    
     public function recentPosts()
    {
        
         $q = $this->createQuery('c')
         ->orderBy('c.created_at DESC')
         ->limit(5);        
         return $q->execute();
        
    }
    
    public function popularPosts()
    {
        
         $q = $this->createQuery('c')
         ->select('c.title,COUNT(*) as count')
         ->leftJoin('c.comments a')
         ->where('c.id=a.post_id')
         ->groupBy('c.id')
         ->orderBy('count desc')
         ->limit(5);        
         return $q->execute();
        
    }
    
}