posts:
  class:    sfDoctrineRouteCollection
  options:  { module: posts, model: post }

welcome:
  url:   /
  param: { module: welcome, action: index }


comments:
  class:    sfDoctrineRouteCollection
  options:  { module: comments, model: comment, prefix_path: /posts/:post_id/comments }